Repository webdesignerrps/photoshop-effects, pull requests merged in 2022-10, with the labels that each got.

#1 update readme.md
  effect by dcrypt/readme.md
Labels: good first issue

#4 Fixed: Introduction editor
  README.md
Labels: documentation, enhancement

#3 Update readme.md
  effect by dcrypt/readme.md
Labels: enhancement
